immutable: false
kind: ConfigMap
metadata:
  name: monkey-tools-vllm-config
apiVersion: v1
data:
  config.yaml: |
    server:
      # defaults to run on port 3000
      port: 3000
    llmInferServer:
      hosts: 
