fullnameOverride:

images:
  sandbox:
    registry: docker.io
    repository: infmonkeys/monkey-tools-sandbox
    tag: 0.0.2
    pullPolicy: IfNotPresent
    pullSecrets: 

  piston:
    registry: docker.io
    repository: ghcr.io/engineer-man/piston
    tag: latest
    pullPolicy: IfNotPresent
    pullSecrets: 

sandbox:
  replicas: 1
  resources:
    limits:
      cpu: '2'
      memory: 8Gi
    requests:
      cpu: '1'
      memory: 2Gi
  nodeSelector: {}
  affinity: {}
  tolerations: []
  service:
    annotations: {}
    labels: {}
    clusterIP: ""

piston:
  enabled: false
  replicas: 1
  timeouts:
    runTimeout: 3600000
    compileTimeout: 3600000
  resources:
    limits:
      cpu: '2'
      memory: 8Gi
    requests:
      cpu: '1'
      memory: 2Gi
  nodeSelector: {}
  affinity: {}
  tolerations: []
  extraEnv:
    - name: PISTON_RUN_TIMEOUT
      value: "3600000"
    - name: PISTON_COMPILE_TIMEOUT
      value: "3600000"
    - name: PISTON_OUTPUT_MAX_SIZE
      value: "1024000"
    - name: PISTON_DISABLE_NETWORKING
      value: "false"
  persistence:
    annotations:
      helm.sh/resource-policy: keep
    persistentVolumeClaim:
      existingClaim: ""
      ## Dify App Data Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.
      ## ReadWriteMany access mode required for nginx
      ##
      storageClass:
      accessModes:
        - ReadWriteMany
      size: 10Gi
      subPath: ""
    hostPath:
      path: "/piston"
      type: "DirectoryOrCreate"
  service:
    annotations: {}
    labels: {}
    clusterIP: ""

###################################
# External redis: This is only required when piston is enabled
###################################
# standalone example
# externalRedis:
#   mode: standalone
#   url: redis://:monkeys123@monkeys-redis-master:6379

# cluster example
# externalRedis:
#   mode: cluster
#   nodes:
#     - host: 127.0.0.1
#       port: 7001
#     - host: 127.0.0.1
#       port: 7002
#     - host: 127.0.0.1
#       port: 7003
#     - host: 127.0.0.1
#       port: 7004
#     - host: 127.0.0.1
#       port: 7005
#     - host: 127.0.0.1
#       port: 7006
#   options:
#     password: password

# sentinel example
# externalRedis:
#   mode: sentinel
#   sentinels:
#     - host: 127.0.0.1
#       port: 7101
#   sentinelName: mymaster
#   options:
#     password: password
