fullnameOverride:

images:
  server:
    registry: docker.io
    repository: infmonkeys/monkey-tools-internet
    tag: 0.0.9
    pullPolicy: IfNotPresent
    pullSecrets: 

server:
  service:
    annotations: {}
    labels: {}
    clusterIP: ""
  resources: {}

tavily:
  apikey:

jinaai:
  apikey:

proxy:
  enabled: false
  url: ""
