fullnameOverride:

images:
  server:
    registry: docker.io
    repository: infmonkeys/monkey-tools-internet
    tag: 0.0.9
    pullPolicy: IfNotPresent
    pullSecrets: 

server:
  replicas: 1
  resources:
    limits:
      cpu: '2'
      memory: 8Gi
    requests:
      cpu: '1'
      memory: 2Gi
  nodeSelector: {}
  affinity: {}
  tolerations: []
  service:
    annotations: {}
    labels: {}
    clusterIP: ""

tavily:
  apikey:

jinaai:
  apikey:

proxy:
  enabled: false
  url: ""
