{{- if and .Values.conductorUi.enabled}}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
{{ include "monkeys.ud.annotations" . | indent 4 }}
    descriptions: conductor-ui
  labels:
{{- include "monkeys.labels" . | nindent 4 }}
    component: conductor-ui
{{ include "monkeys.ud.labels" . | indent 4 }}
  name: {{ template "monkeys.conductorUi.fullname" . }}
spec:
  replicas: {{ .Values.conductorUi.replicas }}
  selector:
    matchLabels:
{{- include "monkeys.selectorLabels" . | nindent 6 }}
      component: conductor-ui
  template:
    metadata:
      annotations:
{{ include "monkeys.ud.annotations" . | indent 8 }}
      labels:
{{- include "monkeys.selectorLabels" . | nindent 8 }}
        component: conductor-ui
{{ include "monkeys.ud.labels" . | indent 8 }}
    spec:
      enableServiceLinks: false
      {{- if .Values.images.conductorUi.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.images.conductorUi.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
        - image: "{{ .Values.images.conductorUi.registry }}/{{ .Values.images.conductorUi.repository }}:{{ .Values.images.conductorUi.tag }}"
          imagePullPolicy: "{{ .Values.images.conductorUi.pullPolicy }}"
          name: conductor-ui
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          resources:
            {{- toYaml .Values.conductorUi.resources | nindent 12 }}
          env:
            - name: WF_SERVER
              value: http://{{ template "monkeys.conductor.fullname" . }}:8080
{{- end}}
