{{- if and .Values.proxy.enabled}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "monkeys.proxy.fullname" . }}
data:
  proxy.conf: |-
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_buffering off;
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
  nginx.conf: |-
    user  nginx;
    worker_processes  auto;
    {{- if .Values.proxy.log.persistence.enabled }}
    error_log  {{ .Values.proxy.log.persistence.mountPath }}/error.log notice;
    {{- end }}
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

    {{- if .Values.proxy.log.persistence.enabled }}
        access_log  {{ .Values.proxy.log.persistence.mountPath }}/access.log  main;
    {{- end }}

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;
        client_max_body_size 15M;

        include /etc/nginx/conf.d/*.conf;
    }

  default.conf: |-
    server {
        listen 80;
        server_name _;

        location /api {
          proxy_pass http://{{ template "monkeys.server.fullname" . }}:{{ .Values.server.service.port }};
          include proxy.conf;
        }

        location /v1 {
          proxy_pass http://{{ template "monkeys.server.fullname" . }}:{{ .Values.server.service.port }};
          include proxy.conf;
        }

        {{- if and .Values.admin.enabled}}
        location /admin {
          proxy_pass http://{{ template "monkeys.admin.fullname" . }}:{{ .Values.admin.service.port }};
          include proxy.conf;
        }
        {{- end}}

        location /openapi {
          proxy_pass http://{{ template "monkeys.server.fullname" . }}:{{ .Values.server.service.port }};
          include proxy.conf;
        }

        location /openapi-json {
          proxy_pass http://{{ template "monkeys.server.fullname" . }}:{{ .Values.server.service.port }};
          include proxy.conf;
        }

        location / {
          proxy_pass http://{{ template "monkeys.web.fullname" . }}:{{ .Values.web.service.port }};
          include proxy.conf;
        }
    }

{{- range $key, $value := .Values.extraConfigFiles }}
  {{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}
{{- end }}
