apiVersion: ghippo.io/v1alpha1
kind: NavigatorCategory
metadata:
  name: smart-application # 命名规则：由小写的"spec.name"与"-custom"而成
spec:
  name: 智能应用 # 若是用于修改category
  isCustom: true # 该字段必须为true
  localizedName: # 定义分类的中英文名称
    zh-CN: 智能应用
    en-US: Smart Application
