immutable: false
kind: ConfigMap
metadata:
  name: monkey-tools-public-media-helper
apiVersion: v1
data:
  config.yaml: |
    server:
      port: 3000

    s3:
    {{- toYaml .Values.externalS3 | nindent 6 }}
