immutable: false
kind: ConfigMap
metadata:
  name: monkey-tools-knowledge-base
apiVersion: v1
data:
  config.yaml: |
    server:
      port: 5000

    database:
      {{- toYaml .Values.externalPostgresql | nindent 6 }}

    redis:
      {{- toYaml .Values.externalRedis | nindent 6 }}

    vector:
      # Vector store type: elasticsearch, pgvector
      {{- if .Values.externalElasticsearchVectorStore.enabled }}
      type: elasticsearch
      elasticsearch:
        url: {{ .Values.externalElasticsearchVectorStore.url }}
        username: {{ .Values.externalElasticsearchVectorStore.username }}
        password: {{ .Values.externalElasticsearchVectorStore.password }}
      {{- else if .Values.externalPGVectorStore.enabled }}
      type: pgvector
      pgvector:
        url: {{ .Values.externalPGVectorStore.url }}
      {{- else }}
      {{- end }}

    {{- if .Values.embeddingsModels }}
    embeddings:
      {{- toYaml .Values.embeddingsModels | nindent 6 }}
    {{- end }}
