immutable: false
kind: ConfigMap
metadata:
  name: monkey-tools-knowledge-base
apiVersion: v1
data:
  config.yaml: |
    server:
      port: 5000

    database:
      url: {{ .Values.externalPostgresql.url }}

    redis:
      {{- toYaml .Values.externalRedis | nindent 6 }}

    vector:
      type: {{ .Values.server.storage.vector.type }}
      {{- if eq .Values.server.storage.vector.type "elasticsearch" }}
      elasticsearch:
        url: {{ .Values.externalElasticsearch.url }}
        username: {{ .Values.externalElasticsearch.username }}
        password: {{ .Values.externalElasticsearch.password }}
      {{- else if eq .Values.server.storage.vector.type "pgvector" }}
      pgvector:
        url: {{ .Values.externalPGVector.url }}
      {{- else }}
      {{- end }}

    embeddings:
      {{- toYaml .Values.server.embeddings | nindent 6 }}
