fullnameOverride:

images:
  server:
    repository: infmonkeys/monkey-tools-knowledge-base
    tag: 0.0.15
    pullPolicy: IfNotPresent
    pullSecrets: 

server:
  service:
    annotations: {}
    labels: {}
    clusterIP: ""

  embeddings:
    models:
      - name: BAAI/bge-base-zh-v1.5
        dimension: 768
      - name: jinaai/jina-embeddings-v2-base-en
        dimension: 768
      - name: jinaai/jina-embeddings-v2-small-en
        dimension: 512
      - name: moka-ai/m3e-base
        dimension: 768

  storage:
    vector:
      type: elasticsearch
    relational:
      type: sqlite

###################################
# External elasticsearch 8
###################################
externalElasticsearch:
  url: http://elasticsearch-master:9200
  username: elastic
  password: monkeys123

###################################
# External postgres
###################################
externalPostgresql:
  url: postgresql://monkeys:monkeys123@monkeys-postgresql:5432/monkeys
  pool:
    pool_size: 30
    pool_recycle: 3600

###################################
# External redis
###################################
externalRedis:
  mode: standalone
  url: redis://:monkeys123@monkeys-redis-master:6379

# cluster example
# externalRedis:
#   mode: cluster
#   nodes:
#     - host: 127.0.0.1
#       port: 7001
#     - host: 127.0.0.1
#       port: 7002
#     - host: 127.0.0.1
#       port: 7003
#     - host: 127.0.0.1
#       port: 7004
#     - host: 127.0.0.1
#       port: 7005
#     - host: 127.0.0.1
#       port: 7006
#   password: password

# sentinel example
# externalRedis:
#   mode: sentinel
#   sentinels:
#     - host: 127.0.0.1
#       port: 7101
#   sentinelName: mymaster
#   password: password


###################################
# External PGVector
###################################
externalPGVector:
  url: postgresql://postgres:postgres@localhost:5432/monkeys
