apiVersion: v1
kind: Service
metadata:
  name: {{ template "monkey-tools-knowledge-base.server.fullname" . }}
  labels:
{{ include "monkey-tools-knowledge-base.labels" . | indent 4 }}
{{- if .Values.server.service.labels }}
{{ toYaml .Values.server.service.labels | indent 4 }}
{{- end }}
    component: "knowledge-base"
{{- with .Values.server.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: ClusterIP
  {{- if .Values.server.service.clusterIP }}
  clusterIP: {{ .Values.server.service.clusterIP }}
  {{- end }}
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
{{ include "monkey-tools-knowledge-base.selectorLabels" . | indent 4 }}
    component: "server"
