immutable: false
kind: ConfigMap
metadata:
  name: monkey-tools-knowledge-base
apiVersion: v1
data:
  config.yaml: |
    server:
      port: 5000

    database:
      url: {{ .Values.externalPostgresql.url }}

    redis:
      url: {{ .Values.externalRedis.url }}

    vector:
      type: elasticsearch
      elasticsearch:
        url: {{ .Values.externalElasticsearch.url }}
        username: {{ .Values.externalElasticsearch.username }}
        password: {{ .Values.externalElasticsearch.password }}

    embeddings:
      {{- toYaml .Values.server.embeddings | nindent 6 }}
