apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
{{ include "monkey-tools-midjourney.ud.annotations" . | indent 4 }}
    descriptions: Midjourney server
  labels:
{{- include "monkey-tools-midjourney.labels" . | nindent 4 }}
    component: server
{{ include "monkey-tools-midjourney.ud.labels" . | indent 4 }}
  name: {{ template "monkey-tools-midjourney.server.fullname" . }}
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
{{- include "monkey-tools-midjourney.selectorLabels" . | nindent 6 }}
      component: server
  template:
    metadata:
      annotations:
{{ include "monkey-tools-midjourney.ud.annotations" . | indent 8 }}
      labels:
{{- include "monkey-tools-midjourney.selectorLabels" . | nindent 8 }}
        component: server
{{ include "monkey-tools-midjourney.ud.labels" . | indent 8 }}
    spec:
      enableServiceLinks: false
      {{- if .Values.images.server.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.images.server.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
        - image: "{{ .Values.images.server.repository }}:{{ .Values.images.server.tag }}"
          imagePullPolicy: "{{ .Values.images.server.pullPolicy }}"
          name: server
          ports:
            - name: http-server
              containerPort: 3000
              protocol: TCP
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /usr/src/app/config.yaml
              name: monkey-tools-midjourney
              readOnly: true
              subPath: config.yaml
      volumes:
        - configMap:
            defaultMode: 420
            name: monkey-tools-midjourney
          name: monkey-tools-midjourney
