{{- if and .Values.clash.enabled}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "monkeys.clash.fullname" . }}
data:
  env: |-
    export CLASH_URL='{{ .Values.clash.subscriptionUrl }}'
    export CLASH_SECRET='{{ .Values.clash.secret }}'
