{{- if .Values.clash.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "monkeys.clash.fullname" . }}
  labels:
{{ include "monkeys.labels" . | indent 4 }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
{{- if .Values.clash.enabled }}
    component: "clash"
{{- end }}
{{- with .Values.clash.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: ClusterIP
  ports:
    - name: http-clash
      port: 7890
      protocol: TCP
      targetPort: 7890
    - name: http-dashboard
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
{{ include "monkeys.selectorLabels" . | indent 4 }}
    component: "clash"
{{- end}}