immutable: false
kind: ConfigMap
metadata:
  name: {{ template "monkeys.server.fullname" . }}
apiVersion: v1
data:
  config.yaml: |
    # Server config
    server:
    {{- toYaml .Values.server.server | nindent 6 }}

    servers:
    {{- toYaml .Values.server.servers | nindent 6 }}

    # Database Config
    {{- if .Values.postgresql.enabled }}
    database:
      type: postgres
      host: {{ .Release.Name }}-postgresql
      port: 5432
      username: {{ .Values.postgresql.global.postgresql.auth.username }}
      password: {{ .Values.postgresql.global.postgresql.auth.password }}
      database: {{ .Values.postgresql.global.postgresql.auth.database }}
    {{- else if .Values.externalPostgresql.enabled }}
    database:
      type: postgres
      host: {{ .Values.externalPostgresql.host }}
      port: {{ .Values.externalPostgresql.port }}
      username: {{ .Values.externalPostgresql.username }}
      password: {{ .Values.externalPostgresql.password }}
      database: {{ .Values.externalPostgresql.database }}
    {{- else }}
    database:
      type: better-sqlite3
      database: data/db.sqlite
    {{- end }}

    # Redis Config
    {{- if .Values.redis.enabled }}
    redis:
      url: redis://:{{ .Values.redis.global.redis.password }}@monkeys-redis-master:6379/0
    {{- else if .Values.externalRedis.enabled }}
    redis:
      {{- toYaml .Values.externalRedis | nindent 6 }}
    {{- else }}
    {{- end }}

    # Auth Config
    auth:
    {{- toYaml .Values.server.auth | nindent 6 }}

    {{- if .Values.minio.enabled }}
    s3:
      endpoint: {{ .Values.minio.endpoint }}
      isPrivate: {{ .Values.minio.isPrivate }}
      accessKeyId: {{ if .Values.minio.accessKeyId }}{{ .Values.minio.accessKeyId }}{{ else }}{{ .Values.minio.auth.rootUser }}{{ end }}
      secretAccessKey: {{ if .Values.minio.secretAccessKey }}{{ .Values.minio.secretAccessKey }}{{ else }}{{ .Values.minio.auth.rootPassword }}{{ end }}
      region: 'us-east-1'
      bucket: {{ .Values.minio.defaultBuckets }}
      publicAccessUrl: {{ .Values.minio.endpoint }}/{{ .Values.minio.defaultBuckets }}
    {{- else if .Values.externalS3.enabled }}
    s3:
      isPrivate: {{ .Values.externalS3.isPrivate }}
      endpoint: {{ .Values.externalS3.endpoint }}
      accessKeyId: {{ .Values.externalS3.accessKeyId }}
      secretAccessKey: {{ .Values.externalS3.secretAccessKey }}
      region: {{ .Values.externalS3.region }}
      bucket: {{ .Values.externalS3.bucket }}
      publicAccessUrl: {{ .Values.externalS3.publicAccessUrl }}
    {{- else }}
    {{- end }}

    conductor:
      baseUrl: http://{{ template "monkeys.conductor.fullname" . }}:8080/api

    models:
    {{- toYaml .Values.server.models | nindent 6 }}
