fullnameOverride:

images:
  server:
    repository: infmonkeys/monkey-tools-comfyui
    tag: 0.0.2
    pullPolicy: IfNotPresent
    pullSecrets: 

server:
  service:
    annotations: {}
    labels: {}
    clusterIP: ""

###################################
# External s3 storage
###################################
externalS3:
  endpoint: ""
  accessKeyId: ""
  secretAccessKey: ""
  region: ""
  bucket: ""
  publicAccessUrl: ""
