immutable: false
kind: ConfigMap
metadata:
  name: monkey-tools-sandbox
apiVersion: v1
data:
  config.yaml: |
    server:
      port: 3000

    {{- if .Values.piston.enabled }}
    piston:
      enabled: true
      apiServer: http://{{ template "monkey-tools-sandbox.piston.fullname" . }}:2000
      runTimeout: {{ .Values.piston.timeouts.runTimeout }}
      compileTimeout: {{ .Values.piston.timeouts.compileTimeout }}

    redis:
      {{- toYaml .Values.externalRedis | nindent 6 }}
    {{- end }}
