fullnameOverride:

images:
  comfyui:
    repository: infmonkeys/comfyui
    tag: 0.0.2-gpu
    pullPolicy: IfNotPresent
    pullSecrets:

comfyui:
  replicas: 1
  resources:
    limits:
      cpu: "4"
      memory: 64Gi
      nvidia.com/gpu: 1
    requests:
      cpu: "4"
      memory: 64Gi

  env:
    # Use external proxy
    - name: http_proxy
      value: ""
    - name: https_proxy
      value: ""

    # Use internal proxy
    - name: CLASH_SUBSCRIPTION_URL
      value: ""
    - name: CLASH_SECRET
      value: ""

    # s3 configuration
    - name: S3_ENABLED
      value: "true"
    - name: S3_ENDPOINT_URL
      value: ""
    - name: S3_ACCESS_KEY_ID
      value: ""
    - name: S3_SECRET_ACCESS_KEY
      value: ""
    - name: S3_REGION
      value: ""
    - name: S3_BUCKET
      value: ""
    - name: S3_PUBLIC_ACCESS_URL
      value: ""
    - name: S3_ADDRESSING_STYLE
      value: "virtual"

    # Auto update comfyfile
    - name: AUTO_UPGRADE_COMFYFILE
      value: "true"

# ClusterIP Mode
service:
  type: ClusterIP
  port: 8188
  clusterIP: ""
  labels:
  annotations:

# NodePort Mode
# service:
#   type: NodePort
#   port: 8188
#   nodePort: 30818

volume:
  models:
    claimName: comfyui-models
  customNodes:
    claimName: comfyui-custom-nodes
  input:
    claimName: comfyui-input
  output:
    claimName: comfyui-output
  venv:
    claimName: comfyui-venv
  huggingface:
    claimName: comfyui-huggingface
