apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
{{ include "monkeys.ud.annotations" . | indent 4 }}
    descriptions: server
  labels:
{{- include "monkeys.labels" . | nindent 4 }}
    component: server
{{ include "monkeys.ud.labels" . | indent 4 }}
  name: {{ template "monkeys.server.fullname" . }}
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
{{- include "monkeys.selectorLabels" . | nindent 6 }}
      component: monkeys
  template:
    metadata:
      annotations:
{{ include "monkeys.ud.annotations" . | indent 8 }}
      labels:
{{- include "monkeys.selectorLabels" . | nindent 8 }}
        component: monkeys
{{ include "monkeys.ud.labels" . | indent 8 }}
    spec:
      enableServiceLinks: false
      {{- if .Values.server.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.server.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
        - image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: "{{ .Values.server.image.pullPolicy }}"
          name: monkeys
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/monkeys/config.yaml
              name: monkeys-config
              readOnly: true
              subPath: config.yaml
      volumes:
        - configMap:
            defaultMode: 420
            name: monkeys-config
          name: monkeys-config
