apiVersion: v1
kind: Service
metadata:
  name: {{ template "comfyui.comfyui.fullname" . }}
  labels:
{{ include "comfyui.labels" . | indent 4 }}
{{- if .Values.comfyui.service.labels }}
{{ toYaml .Values.comfyui.service.labels | indent 4 }}
{{- end }}
    component: "comfyui"
{{- with .Values.comfyui.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if (or (eq .Values.service.type "ClusterIP") (empty .Values.service.type)) }}
  type: ClusterIP
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
{{- else }}
  type: NodePort
{{- end }}
  ports:
    - name: http
      port: 8188
      protocol: TCP
      targetPort: 8188
{{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
      nodePort: {{.Values.service.nodePort}}
{{- end }}
  selector:
{{ include "comfyui.selectorLabels" . | indent 4 }}
    component: "comfyui"
